---
title: "Curso de Redação Científica - Professor Dr. Valtencir Zucolotto"
author: "Jeanne Franco"
date: "05-01-2023"
categories: [Ciência, Pesquisa]
lang: pt
---

Nesta postagem, eu trago um resumo que elaborei durante o Curso de Outono em Escrita Científica realizado nos dias 17, 18, 24 e 25 de abril de 2024 pelo professor [Dr. Valtencir Zucolotto](https://www.linkedin.com/in/valtencir-zucolotto-a0ab3596/) 

Valtencir Zucolotto é professor titular do Instituto de física da USP de São Carlos, possui doutorado em Ciência e Engenharia de Materiais pela Universidade de São Paulo (2003) e coordena o grupo de pesquisa de Nanomedicina e Nanotoxicologia com aplicação nas áreasda saúde e do agronegócio. Zuzolotto foi professor Visitante na Universidade Joseph Fourier, Grenoble, França, em 2010. Desenvolveu e ministra cursos em Escrita Científica, e já publicou mais de 128 artigos em revistas internacionais e 8 capítulos de livros.

Outras informações sobre o professor Dr. Valtencir Zicolotto, seus cursos e materiais de estudo para download você encontra [aqui](https://escritacientifica.com/en/index.html).

